### ISSUE TITLE
ConcurrentModificationException in OnSubscribeFromIterable

### ISSUE THREAD

**Issue by bbednarek** [ReactiveX/RxJava#2839] opened 2015-03-19 11:04 UTC
```
! java.util.ConcurrentModificationException: null
! at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:394) ~[na:1.7.0_60]
! at java.util.LinkedHashMap$KeyIterator.next(LinkedHashMap.java:405) ~[na:1.7.0_60]
! at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:96) ~[rxjava-1.0.8.jar:1.0.8]
! at rx.Subscriber.setProducer(Subscriber.java:177) ~[rxjava-1.0.8.jar:1.0.8]
! at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:47) ~[rxjava-1.0.8.jar:1.0.8]
! at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:33) ~[rxjava-1.0.8.jar:1.0.8]
! at rx.Observable.unsafeSubscribe(Observable.java:7495) ~[rxjava-1.0.8.jar:1.0.8]
! at rx.internal.operators.OperatorConcat$ConcatSubscriber.subscribeNext(OperatorConcat.java:176) ~[rxjava-1.0.8.jar:1.0.8]
! at rx.internal.operators.OperatorConcat$ConcatSubscriber.onNext(OperatorConcat.java:141) ~[rxjava-1.0.8.jar:1.0.8]
! at rx.internal.operators.OperatorConcat$ConcatSubscriber.onNext(OperatorConcat.java:78) ~[rxjava-1.0.8.jar:1.0.8]
! at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:96) ~[rxjava-1.0.8.jar:1.0.8]
! at rx.Subscriber.setProducer(Subscriber.java:177) ~[rxjava-1.0.8.jar:1.0.8]
! at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:47) ~[rxjava-1.0.8.jar:1.0.8]
! at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:33) ~[rxjava-1.0.8.jar:1.0.8]
! at rx.Observable$1.call(Observable.java:144) ~[rxjava-1.0.8.jar:1.0.8]
! at rx.Observable$1.call(Observable.java:136) ~[rxjava-1.0.8.jar:1.0.8]
! at rx.Observable$1.call(Observable.java:144) ~[rxjava-1.0.8.jar:1.0.8]
! at rx.Observable$1.call(Observable.java:136) ~[rxjava-1.0.8.jar:1.0.8]
! at rx.Observable$1.call(Observable.java:144) ~[rxjava-1.0.8.jar:1.0.8]
! at rx.Observable$1.call(Observable.java:136) ~[rxjava-1.0.8.jar:1.0.8]
! at rx.Observable$1.call(Observable.java:144) ~[rxjava-1.0.8.jar:1.0.8]
! at rx.Observable$1.call(Observable.java:136) ~[rxjava-1.0.8.jar:1.0.8]
! at rx.Observable$1.call(Observable.java:144) ~[rxjava-1.0.8.jar:1.0.8]
! at rx.Observable$1.call(Observable.java:136) ~[rxjava-1.0.8.jar:1.0.8]
! at rx.Observable$1.call(Observable.java:144) ~[rxjava-1.0.8.jar:1.0.8]
! at rx.Observable$1.call(Observable.java:136) ~[rxjava-1.0.8.jar:1.0.8]
! at rx.Observable.unsafeSubscribe(Observable.java:7495) ~[rxjava-1.0.8.jar:1.0.8]
! at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62) ~[rxjava-1.0.8.jar:1.0.8]
! at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) ~[rxjava-1.0.8.jar:1.0.8]
! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) ~[na:1.7.0_60]
! at java.util.concurrent.FutureTask.run(FutureTask.java:262) ~[na:1.7.0_60]
! at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178) ~[na:1.7.0_60]
! at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292) ~[na:1.7.0_60]
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[na:1.7.0_60]
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[na:1.7.0_60]
! at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_60]
```

**Comment by akarnokd** [comment] 2015-03-19 11:27
Some other thread or activity is modifying your map while you are observing it.

**Comment by daschl** [comment] 2015-04-24 14:00
@akarnokd I have a similar problem, I don't know if its related. What do you think about that (full stack here https://issues.couchbase.com/browse/JCBC-753)?

```
Caused by: java.util.ConcurrentModificationException
at java.util.HashMap$HashIterator.nextEntry(HashMap.java:894)
at java.util.HashMap$ValueIterator.next(HashMap.java:922)
at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:96)
at rx.Subscriber.setProducer(Subscriber.java:139)
at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:47)
at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:33)
at rx.Observable.unsafeSubscribe(Observable.java:7304)
... 58 more
```

In particular, this Observable is a `PublishSubject` and we are potentially pushing stuff in there from multiple threads. I thought that subject is thread safe, is there anything additional I need to do in that case?

**Comment by daschl** [comment] 2015-04-24 14:05
@akarnokd I just found this gist by accident from @benjchristensen https://gist.github.com/benjchristensen/04eef9ca0851f3a5d7bf#file-eventbuswithparallelprocessing-java-L75 .. looks like my gut feeling was right?

**Comment by akarnokd** [comment] 2015-04-24 14:08
You get CME if the underlying collection you iterating over with ```from()``` changes:
```java
List<Integer> list = new ArrayList<>(Arrays.asList(1, 2, 3));
Observable.from(list).doOnNext(e -> list.remove(0)).subscribe(System.out::print);
```
This is not specific to RxJava.

Subjects are Observers and as such require that their onXXX methods are called sequentially. If you want to call onNext from different threads, you need to serialize this front externally or via ```Subject.toSerialized()```.

**Comment by daschl** [comment] 2015-04-24 14:09
@akarnokd we should get this on the javadocs in the subjects :)

**Comment by akarnokd** [comment] 2015-04-24 14:13
I've recently made an [eventbus example](https://gist.github.com/akarnokd/16e8e30d21e2ff5349e7#file-rxeventbus-java-L14).

I thought that since the sequential requirement of ```Observer``` is documented, by extension, Subject implementing Observer must have inherited this requirement as well.

(BTW, what's the deal with this event bus thing? Everyone seems to want one of these.)

**Comment by daschl** [comment] 2015-04-24 14:18
actually in my case it's a configuration subject where I have 1 subscriber, but many threads can potentially push new configs in..

**Comment by akarnokd** [comment] 2015-04-24 14:19
Can you point me to the code in question?

**Comment by daschl** [comment] 2015-04-24 14:24
Sure!

So it gets created here (right now its not serialized): https://github.com/couchbase/couchbase-jvm-core/blob/master/src/main/java/com/couchbase/client/core/config/DefaultConfigurationProvider.java#L173

And it gets onNext'ed here: https://github.com/couchbase/couchbase-jvm-core/blob/master/src/main/java/com/couchbase/client/core/config/DefaultConfigurationProvider.java#L395 .. this can happen from N threads

And here we are subscribing, this is where it did blow up: https://github.com/couchbase/couchbase-jvm-core/blob/master/src/main/java/com/couchbase/client/core/RequestHandler.java#L146

**Comment by akarnokd** [comment] 2015-04-24 14:35
[L365](https://github.com/couchbase/couchbase-jvm-core/blob/master/src/main/java/com/couchbase/client/core/RequestHandler.java#L365):
```
return Observable.from(nodes).doOnNext(new Action1<Node>() {
    @Override
    public void call(Node node) {
         removeNode(node); // <---------- calls node.remove() !
         node.disconnect().subscribe();
    }
})
```
So I guess nodes is a plain ```HashSet``` which will throw. If it is not big, I'd copy it for ```from()``` and then freely delete from the original.

In addition, I'd create this config subject with ```toSynchronized()``` unless you need to peek into its state in which case for those cases, keep the original ```PublishSubject```.

**Comment by daschl** [comment] 2015-04-24 14:37
@akarnokd good points! I'll fix both the remove issue here as well as making the subject serialized. It's not on the hot code path, so it's better to play safe here.

**Comment by akarnokd** [comment] 2015-04-24 14:41
Great. I'm closing this issue. It is not a bug in RxJava and without further details from the OP, we can't really help him spot the bug.

**Comment by daschl** [comment] 2015-04-24 14:42
works for me, thanks for the help as always @akarnokd.

**Closed by akarnokd** 2015-04-24 14:41 UTC
Labels: Question
