### ISSUE TITLE
Single.zip with Iterable<T> overload does not call given zipper function

### ISSUE THREAD

**Issue by SergejIsbrecht** [ReactiveX/RxJava#5912] opened 2018-03-13 10:36 UTC
I have discovered that, invoking Single.zip with an empty Iterable will not call given zipper function. Is this behavior by design? I would expect that the zipper function would be called with an empty object-array. 

```
  @Test
  void singleDoesNothing() {
    Single<Object[]> zip =
        Single.zip(
            Collections.emptyList(),
            objects -> {
              return objects;
            });

    zip.test().assertNotComplete().assertNoValues();
  }
```

Used version: 2.1.7

**Comment by akarnokd** [comment] 2018-03-13 10:40
Yes, this is by design.

**Comment by yuriykulikov** [comment] 2018-03-13 10:48
Hello David,
could you please elaborate? What is the reason for this?

**Comment by akarnokd** [comment] 2018-03-13 11:09
0 sources have no items to zip.

**Comment by yuriykulikov** [comment] 2018-03-13 11:20
It must be at least explicitely mentioned in the documentation. Otherwise there is a lot of confusion, because developers interpret the current javadoc as: "empty Iterable -> empty Array". This is very unfortunate, because an empty Iterable becomes a corner case, which does not always happen, but when it does, nothing happens.

**Comment by akarnokd** [comment] 2018-03-13 11:24
See #5876.

**Comment by artem-zinnatullin** [comment] 2018-03-19 13:45
Guess we could close this as #5876 was merged :)

**Closed as completed** 2018-03-19 13:47 UTC
Labels: Question, 2.x
