### ISSUE TITLE
Function interface return value not annotated NonNull

### ISSUE THREAD

**Issue by DavidDTA** [ReactiveX/RxJava#6694] opened 2019-10-30 22:00 UTC
The absence of this annotation allows Kotlin code to generate null pointer exceptions when using the map operator (for example).  `BiFunction`, `Function3`, etc. do annotate the return value as `@NonNull`.  Adding this annotation would increase type safety and prevent bugs for users of this library.

This is true in the latest versions of 2.x and 3.x.

**Comment by akarnokd** [comment] 2019-10-30 22:16
Duplicate of #6687. 

The problem is that we can't annotate at the call site yet and we can't restrict the declaration site as that causes problems too.

**Closed as completed by akarnokd** 2019-10-30 22:16 UTC
Labels: 2.x, 3.x
