### ISSUE TITLE
2.x concatMapEager should accept 0 for prefetch

### ISSUE THREAD

**Issue by ansman** [ReactiveX/RxJava#5185] opened 2017-03-14 14:55 UTC
The documentation for `concatMapEager` states:
```java
@param prefetch hints about the number of expected source sequence values
```

Which leads me to assume that the following code should work:
```java
Observable.fromIterable(someCollection)
    .concatMapEager(this::performTask, 5, someCollection.size())
```

but it will fail if the collection is empty. Either the documentation should be updated to reflect that 0 is not a valid value or it should accept 0 (and perhaps set it to a default value internally).

**Comment by akarnokd** [comment] 2017-03-14 15:04
Looks like there is a missing validation there as well. PR welcome. Plus, the parameter document should read something like:

`hints about the number of expected values from each inner ObservableSource`

**Comment by akarnokd** [comment] 2017-03-15 16:50
On a second look, this is not a bug in the operator but perhaps the underdocumentation. Prefetch of 0 or negative has no meaning and if you think there won't be any value, use 1 as the prefetch amount.

**Comment by akarnokd** [comment] 2017-03-16 10:18
Closing via #5189.

**Closed as completed by akarnokd** 2017-03-16 10:18 UTC
Labels: Documentation, PR welcome, 2.x
