### ISSUE TITLE
Potential performance issue with flatmap

### ISSUE THREAD

**Issue by malbano** [ReactiveX/RxJava#5699] opened 2017-11-01 22:38 UTC
Hi, 

I was writing a piece of code using flatmap and noticed a behaviour that can potentially impact performances. I ran a profiler that produces a chrome trace as html, attached to this issue. The code is the following:

```java
private PublishSubject<Irrelevant> triggerSubject;

...
triggerSubject = PublishSubject.create();
        triggerSubject
                .observeOn(Schedulers.io())
                .flatMap(new Function<Irrelevant, ObservableSource<Response>>() {
                    @Override
                    public ObservableSource<Response> apply(Irrelevant irrelevant) throws Exception {
                        // someObservable is produced by retrofit2
                        return someObservable;
                    }
                })
                .doOnNext(new Consumer<Response>() {
                    @Override
                    public void accept(Response response) throws Exception {
                        //Do something
                    }
                })
                .hide()
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new ResponseObserver());

triggerSubject.onNext(Irrelevant.INSTANCE);
```

Note that the application is perfectly idle and nothing is published in the subject after that first call (and the trace shows after that call).
Line numbers are visible in each span (tag: "ln"). Specifically, looking at 1 of the methods that takes 400ms, you can look at https://github.com/ReactiveX/RxJava/blob/0a07ac1808f1c0b93746b6f9d550f9f5f4717be6/src/main/java/io/reactivex/internal/operators/observable/ObservableFlatMap.java#L327

Trace: 
[flatmap-perf-issue.html.zip](https://github.com/ReactiveX/RxJava/files/1435923/flatmap-perf-issue.html.zip)

Libraries used:
```
retrofit2         : "com.squareup.retrofit2:retrofit:2.3.0",
retrofit2RxJava2  : "com.jakewharton.retrofit:retrofit2-rxjava2-adapter:1.0.0",
rxandroid2        : "io.reactivex.rxjava2:rxandroid:2.0.1",
rxjava2           : "io.reactivex.rxjava2:rxjava:2.1.6",
```

Also a screenshot here:
<img width="788" alt="screen shot 2017-11-01 at 15 53 03" src="https://user-images.githubusercontent.com/5725243/32301825-cfaf8e82-bf1c-11e7-95f3-ebd45c659f61.png">

**Comment by akarnokd** [comment] 2017-11-01 22:56
I'm not sure what we should see in that trace. I suppose the retrofit call blocks the io() thread when you issue the request and process the response. Since you have only one triggering event, see if `concatMap` has the same pattern or not as `concatMap` is a pass-through for events and doesn't use a per-item synchronization.

**Comment by malbano** [comment] 2017-11-01 23:17
What I'm saying is that network call is complete and I'd expect nothing to happen (in the trace I attached), instead I see these blocks of 400ms.

<img width="1400" alt="screen shot 2017-11-01 at 16 15 28" src="https://user-images.githubusercontent.com/5725243/32302448-fcbf6264-bf1f-11e7-9360-a271c16fe090.png">

Trying with concatMap seems working way better:
[concatmap.html.zip](https://github.com/ReactiveX/RxJava/files/1435997/concatmap.html.zip)

**Comment by ZacSweers** [comment] 2017-11-02 06:33
@malbano are you saying that drain() or poll() spins for a long time? Is every block 400ms or is that just the highest

**Comment by akarnokd** [comment] 2017-11-02 10:32
That repeating 400ms looks odd. What is in `doOnNext`? Does it happen with `Flowable`? Could you provide a standalone example that reproduces the problem?

**Comment by malbano** [comment] 2017-11-22 02:09
I'm sorry for the delay but I've been on vacation. I'll be adding the repro example soon.

Thank you.

**Comment by malbano** [comment] 2017-12-15 17:41
I tried to replicate this many times but didn't manage. At this point I think this can be closed.

**Comment by akarnokd** [comment] 2017-12-15 17:45
Closing for now. Let us know if you get more insight into your problem.

**Closed as completed by akarnokd** 2017-12-15 17:45 UTC
Labels: 2.x
