### ISSUE TITLE
Unordered sequence when using a map in a zip

### ISSUE THREAD

**Issue by RomainPiel** [ReactiveX/RxJava#3221] opened 2015-08-28 09:09 UTC
I'm having a weird issue with RxJava where items come in the wrong order when one of the zip sources is doing a map. This is a simple version of my issue with strings and integers. I know this could be optimised but I'm trying to understand why I'm observing this weird behaviour.

```java
List<Integer> integerList = new ArrayList<>();
for (int i = 0; i < 100; i++) {
    integerList.add(i);
}

Observable<Integer> source = Observable.from(integerList);

Observable<String> zip = Observable.zip(
        source.flatMap(integer -> Observable.just(integer.toString())
                .map(s -> "- " + s)),
        source,

        (s, integer) -> s + " /// " + integer
);

zip.subscribe(System.out::println);
```

This dumb example should print a sequence of 100 lines from 0 to 99 with the format `- 0 /// 0`. Things go well until the 29th item. After that, the first stream comes in a bad order to the zip function:
```
- 0 /// 0
- 1 /// 1
- 2 /// 2
- 3 /// 3
- 4 /// 4
- 5 /// 5
- 6 /// 6
- 7 /// 7
- 8 /// 8
- 9 /// 9
- 10 /// 10
- 11 /// 11
- 12 /// 12
- 13 /// 13
- 14 /// 14
- 15 /// 15
- 16 /// 16
- 17 /// 17
- 18 /// 18
- 19 /// 19
- 20 /// 20
- 21 /// 21
- 22 /// 22
- 23 /// 23
- 24 /// 24
- 25 /// 25
- 26 /// 26
- 27 /// 27
- 39 /// 28
- 40 /// 29
- 41 /// 30
- 42 /// 31
- 43 /// 32
...
```
I am using RxAndroid which is using RxJava version 1.0.14 (I doubt it's related to RxAndroid).

The funny thing is that this issue is solved when I remove the `map`. This prints the strings correctly:
```java
Observable<String> zip = Observable.zip(
        source.flatMap(integer -> Observable.just(integer.toString())),
        source,

        (s, integer) -> s + " /// " + integer
);
```

Any idea? Anything I should not be doing?

**Comment by hannesstruss** [comment] 2015-08-28 09:46
As far as I know, `flatMap` doesn't guarantee order. `concatMap` does: http://reactivex.io/RxJava/javadoc/rx/Observable.html#concatMap(rx.functions.Func1)

**Comment by RomainPiel** [comment] 2015-08-28 09:49
@hannesstruss I just figured that out! Thanks a lot, I'm feeling like a noob right now

**Comment by akarnokd** [comment] 2015-08-28 10:26
Actually, `flatMap` doesn't guarantee order if its consumer is asynchronous. For synchronous case, it should be properly ordered. I've run your example with both 1.0.14 and 2.x and both print everything in order.

Does this reordering happen for you all the time with this example or occasionally?

In addition, due to how `flatMap` optimizes for `just()` it is possible a simple sequence gets reordered in case of async consumption:

```java
Observable.range(1, 1000000)
    .subscribeOn(Schedulers.computation())
    .flatMap(Observable::just)
    .observeOn(Schedulers.computation())
    .toBlocking()
    .forEach(new Action1<Integer>() {
        Integer last;
        @Override
        public void call(Integer t) {
            if (last != null) {
                if (last > t) {
                    System.err.println("Reorder! Last: " + last + ", Current: " + t);
                }
            }
            last = t;
        }
    });
```

**Comment by RomainPiel** [comment] 2015-08-28 10:33
The reordering happened consistently exactly in the same (unordered) order. In my test I was not specifying any kind of schedulers so everything should be happening in the same thread. I don't think I'm the only one who got this behaviour, see this article from @android10 for more details : http://fernandocejas.com/2015/01/11/rxjava-observable-tranformation-concatmap-vs-flatmap/

**Comment by akarnokd** [comment] 2015-08-28 12:09
I run your example 10000 times with Java 8u60 and stock RxJava 1.0.14 but the anomaly didn't happen. 

Prior to 1.0.13, `flatMap` had some bugs in it that affected merging just(). Could you try to change it to `just(...).asObservable()` which hides just and forces the `flatMap` on a different path.

**Comment by RomainPiel** [comment] 2015-08-30 14:45
Wow that's crazy I'm trying to reproduce on a fresh project and I can't get the same output, everything looks ok. Let me find what made it break...

**Comment by RomainPiel** [comment] 2015-08-30 15:15
Alright so I'm still not sure about the exact cause but I found out a few things:
- I could only reproduce in an Android project. I tried reproducing in a fresh java project with the same JDK (7u79) and RxJava version (1.0.13) but the output was always correct in the pure java project.
- Upgrading RxJava to 1.0.14 fixes the issue in the Android project! Even if I'm not sure why it was failing, I can just ping the guys behind RxAndroid to update RxJava to the latest version.
- The `just(...).asObservable()` did not fix anything

**Comment by JakeWharton** [comment] 2015-08-30 15:41
RxAndroid will _never_ be able to track the current release of RxJava because the release schedules are at vastly different frequencies. It's already been updated to point at 1.0.14 but there's no reason to make a release because the actual library hasn't changed. You should always specify the latest RxJava explicitly.

**Comment by RomainPiel** [comment] 2015-08-30 15:49
@jakewharton yes this makes total sense, thanks for your answer

**Comment by JakeWharton** [comment] 2015-08-30 15:57
Will add to RxAndroid README though. I bet it catches a lot of people.

**Comment by akarnokd** [comment] 2016-03-14 00:00
Great, it seems the issue is resolved via updating to a newer version.

**Closed by akarnokd** 2016-03-14 00:00 UTC
Labels: Question
