### ISSUE TITLE
Recursive expand operator

### ISSUE THREAD

**Issue by abersnaze** [ReactiveX/RxJava#5173] opened 2017-03-11 14:54 UTC
I've been working on a problem that involves making recursive async calls to a service but I have had to hack something together using a Subject as queue. I found that RxJS implements an operator called expand. I was wondering if @akarnokd et. al. would like to include this in RxJava.

https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/expand.md
https://gist.github.com/abersnaze/745f3a433436dbaf7ea2ec684160aabf

The I'm thinking the signature for RxJava would looks something like:`Observable<Observable<T>> expand(Func1<T, Observable<T>> selector)`.
The reason that it returns an Observable of Observables is to reduce the number of overloads needed by allowing the user to use one of the many existing concat or merge operators to flatten.

**Comment by akarnokd** [comment] 2017-03-11 15:42
Sounds like an uncommon operator to me that is better suited for rxjava-extras. Also looks like the expansion is driven by the consumption of the inner `Observable` that may lead to unexpected orderings of the values. (I can also imagine some form of depth-first and breath-first expansion strategies as well.)

/cc @davidmoten

**Comment by abersnaze** [comment] 2017-03-11 16:31
> Sounds like an uncommon operator to me that is better suited for rxjava-extras.

I'm building something similar to web spider which I didn't think is that unusual. It is a type of operation not easily done with existing operators. What are the criteria that we should use for submitting to rxjava vs. rxjava-extras? You've said in the past that retrolambda is very good at extracting the relevant parts RxJava and that additional operators are ok.

> Also looks like the expansion is driven by the consumption of the inner Observable that may lead to unexpected orderings of the values. (I can also imagine some form of depth-first and breath-first expansion strategies as well.)

To control for the order `concat` would ensure breadth-first where using `merge` would be fastest-first.

**Comment by akarnokd** [comment] 2017-03-11 17:15
> What are the criteria that we should use for submitting to rxjava vs. rxjava-extras?

1. Is it an instance operator? 
    - If not, it may live outside RxJava.
2. Does it add overloads to an existing operator? 
    - If yes then it can go into RxJava as `@Experimental`
3. Does it add an operator whose cousins are already there in some other base type? 
    - If yes then it can go into RxJava as `@Experimental`
4. Is the operator's behavior properly thought out (concurrency, corner cases)?
    - If not, it should be incubated externally first.
5. Is the operator properly covered with unit tests?
    - If not, it should be incubated externally first.
6. How large or special is the expected target audience?
    - If unknown, small or special, it should be hosted in an external library.
7. Does the operator require new dependencies?
    - If yes, it should be hosted in an external library.
8. Is the committer likely to stay and work out problems with the operator?
    - If not, well, it might not worth the trouble.

> You've said in the past that retrolambda is very good at extracting the relevant parts RxJava and that additional operators are ok.

I don't understand this sentence. Do you mean ProGuard? I can't remember I said that but according to Jake, it is 2.x that doesn't need any ProGuard rules unlike 1.x.

**Comment by vanniktech** [comment] 2017-03-11 18:30
2.x requires no proguard rules at all. Only 1.x did

**Comment by abersnaze** [comment] 2017-03-11 19:52
1. yes
2. no
3. does RxJS count as a cousin.
4. TBD as the gist is a POC and probably shouldn't be the finial operator implementation.
5. TBD see 4
6. Walking tree/graph structures is not an uncommon problem.
7. no
8. I'll probably be around awhile 😄

Yes, I meant proguard as I don't use either I got it mixed up. It might of been @JakeWharton then.

**Comment by JakeWharton** [comment] 2017-03-12 05:47
I have a use case for recursive expand currently as well. Using what is probably the same subject hack as mentioned in the original comment.

**Comment by akarnokd** [comment] 2017-03-12 11:28
Thanks @JakeWharton. Given the feedback, it looks like `expand` could become part of RxJava (rxjava-extras may not be Android friendly). @abersnaze I suggest you work out the details in your local RxJava fork and only post a PR when it has all the docs, unit tests (including all sorts of async expansions) and at least 90% code coverage of the new classes.

**Comment by abersnaze** [comment] 2017-03-12 12:33
@akarnokd Which would you recommend for replacing the subject with?  BackpressureDrainManager?

**Comment by akarnokd** [comment] 2017-03-12 18:41
You'll probably need a custom drain management because of the recursive nature and reentrancy.

**Comment by davidmoten** [comment] 2017-03-13 08:36
:+1:  I'm keen to see some recursive help turn up as well and funnily enough was mulling over a use case last week (perhaps two years ago was the last one that ended up on my plate).

**Comment by davidmoten** [comment] 2017-03-13 08:38
Re *rxjava-extras* android support my recent googling tells me it should be ok (perhaps with appropriate ProGuard rules) but haven't confirmed yet.

**Comment by abersnaze** [comment] 2017-03-13 16:57
In working on this I want to make one overload for detecting and avoiding cycles in a graph.  I'm leaning toward this as the API.

 `public final <S> Observable<Observable<T>> expand(Func1<? super T, ? extends Observable<T>> func, Func0<? extends S> stateFactory, Func2<? super S, ? super T, Boolean> shouldVisit)`

where `stateFactory` would be set to `HashSet::new` and `shouldVisit` as `Set::add`

The problem that I'm working through is that since the operator isn't using merge/concat to serialize 
the output it'll need an internal queue for ensuring non-concurrent & non-blocking invocations of the `func` and `shouldVisit`.

**Comment by akarnokd** [comment] 2017-03-13 17:15
There could be a tip in the javadoc to use `defer` to create a set per consumer to avoid cycles:

```java
Observable.defer(() -> {
    Set<T> set = new HashSet<>();
    return source.expand(v -> {
        if (set.add(v)) {
            return func.call(v);
        }
        return Observable.empty();
    }
});
```

**Comment by abersnaze** [comment] 2017-03-13 17:23
I'm not worried about the `HashSet::new` i'm more worried about concurrent calls to `Set::add`.  Here is a draft of the implementation that I did this weekend. I won't have much time this week to look at it.

https://github.com/abersnaze/RxJava/blob/expand/src/main/java/rx/internal/operators/OnSubscribeExpand.java#L152

**Comment by akarnokd** [comment] 2017-04-11 11:46
Any progress on this? The feature freeze on *June 1, 2017* is closing in, after that you'd be limited to an `Operator` or `Transformer`-based external implementation.

**Comment by abersnaze** [comment] 2017-04-11 15:42
I've stalled on getting unit tests done but I think its mostly functional.

**Comment by akarnokd** [comment] 2017-09-04 06:07
I'm closing this issue due to inactivity. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.

**Closed as completed by akarnokd** 2017-09-04 06:07 UTC
Labels: Feature-Request, 1.x
