### ISSUE TITLE
possible onBackpressureBuffer bug?

### ISSUE THREAD

**Issue by ndori** [ReactiveX/RxJava#4734] opened 2016-10-20 08:58 UTC
[I've opened a question in stackoverflow](http://stackoverflow.com/questions/40149801/rxjava-onbackpressurebuffer-not-emitting-items), but I'm prettry sure that only a handful of developers from the rxJava team will be able to answer it.

I don't consider it a bug yet as I can't explain the behavior. 

I will be happy to hear any comment regard it in here or on stackoverflow

Tnx, Nitzan

**Comment by akarnokd** [comment] 2016-10-20 09:15
Please avoid cross-posting (such immediately); StackOverflow is monitored for possible bugs with RxJava just like now where I gave an answer to your issue. In a rare case that we don't pick up potential bugs from SO for several days, feel free to open an issue then. 

Closing as possibly duplicate of #4735 in the underlying issue.

**Closed as completed by akarnokd** 2016-10-20 09:15 UTC
Labels: Duplicate

**Comment by ndori** [comment] 2016-10-20 09:17
ok, tnx, wasn't sure how to post it.
