### ISSUE TITLE
OSGi Compatibility: Split packages

### ISSUE THREAD

**Issue by redrezo** [ReactiveX/RxJava#2598] opened 2015-02-04 11:59 UTC
if one wants to use rxjava and a plugin like rxmath one runs into the issue of split packages
both libs export the package rx
so if your bundle imports package rx, the runtime needs to choose between the rx packages of the two libs

i propose moving the addional plugin libs into their own namespaces:
rx.math
rx.javafx
...

http://wiki.osgi.org/wiki/Avoid_Split_Packages

**Comment by benjchristensen** [comment] 2015-02-04 18:50
Do you mind submitting pull requests to fix the OSGi behavior on each of the subprojects? I am not experienced with OSGi.

**Comment by redrezo** [comment] 2015-02-05 18:46
the only needed change is to rename the packages to prevent name clashes with the core packages
for example the javafx subproject:

rx.observables    =>  rx.javafx.observables
rx.schedulers     => rx.javafx.schedulers
rx.subscriptions  => rx.javafx.subscriptions
rx.javafx.sources (no need to rename)

But first we need to define a scheme about how subproject namespaces should look like
in the above example it would be rx.<subprojectid>
however this could also lead to splitpackges if the subprojectid happens to collide with one of the core rx packages
another option would be to not reuse the rx. namespace e.g. rx<subprojectid> (without the dot)
rxjavafx.observables

the second point to consider is that renaming the packages is an api breaking change for each subproject. So you need to increment the version numbers depending on your versioning scheme

once you decide on a scheme for the subproject namespaces, i can submit pull requests

**Comment by benjchristensen** [comment] 2015-02-06 21:30
We can't rename java packages. That is a breaking change.

**Comment by benjchristensen** [comment] 2015-02-06 21:30
Also, it is by design that they are the same package names.

**Comment by redrezo** [comment] 2015-02-09 18:56
Could you please reconsider this design choice for the next major release?
Only the subprojects would be affected and it would make the whole rxjava project a good osgi citizen.

**Comment by benjchristensen** [comment] 2015-08-28 17:08
This is not related to RxJava itself, but each of the other projects. So, if you are interested in opening issues on each sub-project for when they adopt RxJava 2.0, that can try and help influence whichever devs manage each individual project.

Closing out.

**Closed by benjchristensen** 2015-08-28 17:08 UTC
Labels: Enhancement
