### ISSUE TITLE
Subscription#addToCompositeSubscription() wanted!

### ISSUE THREAD

**Issue by maomaobug** [ReactiveX/RxJava#4208] opened 2016-07-18 05:57 UTC
When using RxJava in Android development, we write pretty much codes like this

```
Subscription s = someObservable.subscribe(...);
someCompositeSubscription.add(s);
```

```
onDestroy() {
    someCompositeSubscription.unsubscribe();
}
```

I think it will make our code more well-formatted if we have an `addToCompositeSubscription()` instance method on `Subscription`, especially if we apply quite a few operators before we do subscribe. It will also get rid of a temp variable.

Then it will be

```
someObservable
    .<operator>
    ...
    .subscribe(...)
    .addToCompositeSubscription();
```

**Comment by akarnokd** [comment] 2016-07-18 06:57
Duplicate of #4205. We can't and won't change `Subscription`.

**Closed as completed** 2016-08-18 21:00 UTC
Labels: Duplicate
