### ISSUE TITLE
ReplaySubject and Filter, bug or feature?

### ISSUE THREAD

**Issue by Cher80** [ReactiveX/RxJava#4362] opened 2016-08-17 18:04 UTC
Hi, 
I have two subsribers for one ReplaySubject. 
Subscriber1 filters emited objects for type 1   -- replaySubject.filter(1).subscribe()
Subscriber2 filters emited objects for type 2  -- replaySubject.filter(2).subscribe()

I emit from my ReplaySubject objects of types 1,1,1,1,2 (one on click)
Subscriber1 gets 1,1,1,1
then on the next click
Subscriber2 gets 2 and (!INTERSTING!) Subscriber1 gets 1,1,1,1 again.

Looks like there are some logic of ReplaySubject based on if onNext was called (on not called in case of filtering) and force ReplaySubject to reemit the objects 
I can provide simplified code if needed

**Comment by akarnokd** [comment] 2016-08-17 19:28
A small code example would be great.

**Comment by micdm** [comment] 2016-08-22 07:29
I think I caught a similar bug prior to #4051. @Cher80 what version of RxJava do you use?

**Comment by ncanibano** [comment] 2016-08-25 23:39
We found out a similar strange behavior in our app with ReplaySubject and filter duplicating items.
You can reproduce it with this code snippet:

```
object RxTest {

  def main(args: Array[String]): Unit = {
    val subject = ReplaySubject[Int]()

    val result = subject
      .filter(_ > 0)

    result.subscribe(chunk ⇒ println(chunk))

    subject.onNext(1)
    subject.onNext(2)
    subject.onNext(0)
    subject.onNext(3)
    subject.onNext(0)
    subject.onNext(6)
  }

}
```

We are using RxJava v1.1.6 and RxScala v0.26.2.
This is the expected behavior or do you think is there an issue here?

**Comment by akarnokd** [comment] 2016-08-26 06:48
This test passes with 1.1.10 snapshot:

``` java
    @Test
    public void filtered() {
        ReplaySubject<Integer> subject = ReplaySubject.create();

        TestSubscriber<Integer> ts1 = TestSubscriber.create();
        TestSubscriber<Integer> ts2 = TestSubscriber.create();

        Observable<Integer> o = subject.filter(new Func1<Integer, Boolean>() {
            @Override
            public Boolean call(Integer v) {
                return v > 0;
            }
        });

        o.subscribe(ts1);
        o.subscribe(ts2);

        subject.onNext(1);
        subject.onNext(2);
        subject.onNext(0);
        subject.onNext(3);
        subject.onNext(0);
        subject.onNext(6);

        ts1.assertValues(1, 2, 3, 6);
        ts2.assertValues(1, 2, 3, 6);

        subject.onNext(0);
        subject.onNext(7);

        ts1.assertValues(1, 2, 3, 6, 7);
        ts2.assertValues(1, 2, 3, 6, 7);
    }
```

**Comment by ncanibano** [comment] 2016-08-26 12:49
The same test fails in 1.1.6 with this error:

java.lang.AssertionError: Number of items does not match. Provided: 4  Actual: 6.
Provided values: [1, 2, 3, 6]
Actual values: [1, 2, 2, 3, 3, 6](0 completions)

```
at rx.observers.TestObserver.assertionError(TestObserver.java:197)
at rx.observers.TestObserver.assertReceivedOnNext(TestObserver.java:116)
at rx.observers.TestSubscriber.assertReceivedOnNext(TestSubscriber.java:274)
at rx.observers.TestSubscriber.assertValues(TestSubscriber.java:529)
```

Could you please confirm that this was an unknown issue in previous versions? Since which stable version is this error fixed? Thanks!

**Comment by ncanibano** [comment] 2016-08-26 13:06
It seems this issue was fixed in 1.1.7 thanks to #4051 
But we don't know where it was first introduced.
Thanks

**Comment by ncanibano** [comment] 2016-08-26 19:30
It seems that it was recently introduced in version 1.1.6 due to an optimization.
Versions previous to 1.1.6 are working just fine as far as we know.

**Comment by akarnokd** [comment] 2016-09-08 10:48
Yes, there was a bad optimization added in 1.1.6 which has been resolved in the next release. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.

**Closed as completed by akarnokd** 2016-09-08 10:48 UTC
Labels: Question
