### ISSUE TITLE
mergeDelayError throws UndeliverableException

### ISSUE THREAD

**Issue by bpr10** [ReactiveX/RxJava#5267] opened 2017-04-06 06:52 UTC
Using mergeDelayError when we try to dispose the observer and some error had happened in up stream(before disposing) then it throws UndeliverableException. 
As per the documentation mergeDelayError should catch all errors and pass it to the Subscriber at the end of the stream. Once disposed, it shouldn't call onError which is expected but should not crash as well. 

Also if you replace **mergeDelayError with concatDelayError** it doesn't crash. Am I missing something. 

```
Observable.mergeDelayError(
        Observable.error(new Exception("Yay!")),
        Observable.just(1, 2, 3))
        .subscribe(new DisposableObserver<Object>() {
          @Override
          public void onNext(Object value) {
            Log.d("Debug", value + " received");
            if ((Integer) value == 2) {
              dispose();
            }
          }

          @Override
          public void onError(Throwable e) {
            Log.d("Debug", " received error " + e.getMessage());
          }

          @Override
          public void onComplete() {
            Log.d("Debug", "Complete ");
          }
        });

```
**Crash Logs:**
```
io.reactivex.exceptions.UndeliverableException: java.lang.Exception: 
                                                                                       at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:366)
                                                                                       at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.dispose(ObservableFlatMap.java:310)
                                                                                       at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:124)
                                                                                       at io.reactivex.observers.DisposableObserver.dispose(DisposableObserver.java:88)
                                                                                       at com.example.bedprakashrout.rxsample.MainActivity$1.onNext(MainActivity.java:44)
```

**Comment by akarnokd** [comment] 2017-04-06 07:28
Yes, currently when cancelling a `mergeDelayError` mid-sequence, any accumulated exceptions get routed to the plugin error handler which crashes the app on Android. Generally you should install a [global error handler](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling) and decide which undeliverable exception is ignorable and which should crash the application.

`mergeDelayError`'s behavior is unconventional but was designed so because it is the operator that is most commonly involved with stream failures which in 2.x won't be dropped/ignored like in 1.x. 

@JakeWharton what do you think about this particular operator and use case?

**Comment by bpr10** [comment] 2017-04-06 07:51
Let's say the observable was still emitting and the Activity life cycle triggered the disposing. The mid flow disposing is to mock that case. In my production code activity life cycle is the trigger. Currently, we are using the global error handler as a workaround. But this way all the errors gets handled in the global handler and makes handling new issues tough in the long run. Is there any alternative to this approach.
Again, My query is if **concatDelayError** doesn't crash why does **mergeDelayError** ?

**Comment by akarnokd** [comment] 2017-04-06 07:54
Again,

`mergeDelayError`'s behavior is unconventional but was designed so because it is the operator that is most commonly involved with stream failures which in 2.x won't be dropped/ignored like in 1.x.

The problem with such undeliverable errors is that you want certain errors to crash your app while you are fine with dropping others. RxJava can't decide this for anybody and instead offers hooks to deal with the situation.

**Comment by akarnokd** [comment] 2017-07-05 22:25
I'm closing this issue due to inactivity. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.

**Closed as completed by akarnokd** 2017-07-05 22:25 UTC
Labels: Question, 2.x
