### ISSUE TITLE
The picture and text explanation with method named takeLast(int count, long time, TimeUnit unit) is error?

### ISSUE THREAD

**Issue by zy5123299** [ReactiveX/RxJava#4009] opened 2016-06-16 02:38 UTC
```
private Observable<Integer> takeLastTimeCountObservable() {
    return Observable
            .create((Subscriber<? super Integer> subscriber) -> {
                for (int i = 1; i <= 10; i++) {
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                    if (!subscriber.isUnsubscribed()) {
                        subscriber.onNext(i);
                    }
                }
                if (!subscriber.isUnsubscribed()) {
                    subscriber.onCompleted();
                }
            })
            .subscribeOn(Schedulers.io())
            .takeLast(2, 4, TimeUnit.SECONDS)
            .observeOn(AndroidSchedulers.mainThread());
}
```

result:9,10

but,the picture(https://raw.githubusercontent.com/wiki/ReactiveX/RxJava/images/rx-operators/takeLast.tn.png) is mean (7,8) ,isn't it?

**Comment by akarnokd** [comment] 2016-06-17 08:16
The picture is wrong, `takeLast` returns at most the last N values (9, 10 in your example) or fewer if the time window is shorter.

**Comment by DavidMGross** [comment] 2016-06-17 16:46
Duplicate of #3957

**Comment by DavidMGross** [comment] 2016-06-17 16:48
Diagram fixed.

**Closed as completed by DavidMGross** 2016-06-17 16:48 UTC
Labels: Documentation
