### ISSUE TITLE
Request: Single.onErrorResumeNext(Func1<? super Throwable, Single<? extends T>> resumeFunction)

### ISSUE THREAD

**Issue by GrahamRogers** [ReactiveX/RxJava#3731] opened 2016-02-24 18:11 UTC
To match `Observable`'s.

    public Single<V> onErrorResumeNext(Func1<? super Throwable, Single<? extends T>> resumeFunction);

**Comment by rtedin** [comment] 2016-02-25 13:51
We are also interested in this feature. Currently we are in the process of switching `Observable` to `Single` where it makes sense. Not having this feature is blocking us. Since we would use this internally and not expose the details to users, does anybody know a workaround for accessing the `Throwable`?

**Comment by rtedin** [comment] 2016-02-25 14:06
Since we are just interested in mapping the emitted exception to something else, here is something that just occurred to me. It's ugly, but it seems that it works as a temporary workaround in our use case. It may be useful for others too, so here it is:

```java
single.onErrorReturn(throwable -> {
    throw mapException(throwable);
});
```

Where `mapException` maps the `Throwable` to one of our exceptions.

**Comment by vanniktech** [comment] 2016-02-25 14:09
Isn't this a dupe of #3440 ?

**Comment by rtedin** [comment] 2016-02-25 14:11
Yes, you're right. It's a duplicate.

**Closed** 2016-03-15 23:57 UTC
Labels: Feature-Request, PR welcome
