### ISSUE TITLE
2.x inconsistent use of blockingGet() for Completable 

### ISSUE THREAD

**Issue by tjake** [ReactiveX/RxJava#5063] opened 2017-02-03 18:10 UTC
I find the choice of Completable.blockingGet() returning the throwable vs using onError as blockingAwait() does very error prone.  

My reasoning is Single/Observable/Etc all throw the exception with blockingGet().  Keeping in mind the context that a given type is a Completable so requires a special case is very easy to forget.  I think both should call onError and there should be a special case for folks that want to get the actual exception.

**Comment by akarnokd** [comment] 2017-02-03 18:20
Your are mixing a few concepts, there is nothing to call `onError` on when you block for the results of a source. Since `Completable` doesn't have any value, it allows for the opportunity to get the `Throwable` without the need to try-catch it. For the other types, getting the item is more important and since Java doesn't support record types or multi-value returns, the alternate delivery method for these remain rethrowing the exception.

Also it is marked with `@CheckReturnValue` so a static analysis tool/IDE should warn you if you forget to check the returned value.

**Comment by tjake** [comment] 2017-02-03 18:28
> For the other types, getting the item is more important and since Java doesn't support record types or multi-value returns, the alternate delivery method for these remain rethrowing the exception.

Right, which is why IMO we should stick to that for the case of all types.    Returning exceptions is not very common thing in java.

**Comment by akarnokd** [comment] 2017-02-03 18:39
Since 2.x is now stable, we are bound by binary/behavior compatibility on the method. Therefore, changing its signature or making it rethrow instead of return is not possible.

The alternative I can offer is to deprecate it and have an explicit `blockingGetThrowable()` method to make it stand out from others. In this case, I'd also like to ask the opinions of our power-contributors, @JakeWharton, @vanniktech, @davidmoten.

My stance is to keep everything as is and users should learn this peculiarity of RxJava.

**Comment by thobbs** [comment] 2017-02-03 18:42
I also agree with @tjake here.  The fact that Completable has different behavior for `blockingGet()` than Single/Observable/etc do is surprising and potentially dangerous, as it makes it easy for errors to go ignored.  Obviously you cannot break backward compatibility in the 2.x API at this point, but I think it would be good to take some steps to mitigate this (through docs, alternative methods, and deprecation, as needed).

**Comment by tjake** [comment] 2017-02-03 18:46
I agree, and I was raising it as a precaution to point out after using it (2.x is really great btw).

One shorter term solution would be to add a property to change the behavior so people can opt-in vs the current default

**Comment by JakeWharton** [comment] 2017-02-03 19:06
Yeah it's slightly unfortunate we didn't consider anything around this before 2.0.

I do agree that the disparity is a bit weird. It would be nice to have, say, `Throwable blockingGetThrowable()` and `void blockingComplete() throws Throwable` instead of the current `Throwable blockingGet()`.

**Comment by artem-zinnatullin** [comment] 2017-02-03 19:15
So deprecate current method and add new one that throws?

Also, this actually raises question about add @CheckResult as addition to
recent PRs with @Nullable/@NonNull.

**Comment by JakeWharton** [comment] 2017-02-03 19:23
The current method's behavior is perfectly valid. The problem is its name in correlation to the other stream types doesn't match. So it would effectively be a rename (new method + deprecation) of its behavior plus the addition of one which returns `void` and throws.

**Comment by vanniktech** [comment] 2017-02-03 20:27
I'd leave it as is too. While I get the point that it's slightly odd, making it deprecated and creating a new method might cause more confusion than any good. Also since the method is marked as stable it'll never be deleted in 2.x

Also error-prone works really well in the above mentioned case since it'd flag the line if you would not handle the returned Throwable.

**Comment by akarnokd** [comment] 2017-03-20 09:03
Thanks for the feedback. I don't see any compelling case to change the API for this one.

**Closed as completed by akarnokd** 2017-03-20 09:03 UTC
Labels: Discussion, 2.x
