### ISSUE TITLE
Shaded Dependencies for Queues?

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#2964] opened 2015-05-19 16:21 UTC
Right now we pull in source code for performant queue implementations (such as here https://github.com/ReactiveX/RxJava/pull/2963 and here https://github.com/ReactiveX/RxJava/tree/1.x/src/main/java/rx/internal/util/unsafe). 

I'd like to explore whether we can put a shaded dependency on things like JCTools (https://github.com/JCTools/JCTools) and Agrona (https://github.com/real-logic/Agrona) along with specific paths to classes we are interested in so we can:

1) Not need to copy/paste
2) Show proper attribution through dependencies rather than comments in code
3) More easily pick up bug fixes
4) Still only pick up the byte size we want rather than the full libraries
5) Still remain a single-jar, zero dependency artifact when published to maven central

**Comment by zsxwing** [comment] 2015-05-19 17:12
Looks `Agrona` requires JDK8

**Comment by benjchristensen** [comment] 2015-05-19 20:36
Ah yes you're right, only for v2 for Agrona then.

**Comment by akarnokd** [comment] 2015-09-03 08:01
I like JCTools but I also like customizing it for RxJava's needs (i.e., inlining or dropping certain parts of it).

**Comment by nitsanw** [comment] 2016-03-02 09:07
is this not a duplicate of #1735 ?

**Comment by akarnokd** [comment] 2016-06-17 22:39
Closing as a duplicate of #1735 (the discussion is much longer there anyway).

**Closed by akarnokd** 2016-06-17 22:39 UTC
Labels: Build, Duplicate, Enhancement
