### ISSUE TITLE
concat() observed on a busy thread can swallow items

### ISSUE THREAD

**Issue by JoanZapata** [ReactiveX/RxJava#2646] opened 2015-02-10 17:49 UTC
Hi,
Here's my current usecase:

```java
Observable.concat(o1.subscribeOn(..), o2.subscribeOn(...))
   .observeOn(...)
   .subscribe(...)
```
`o1` always emit one element before it completes. (the item is retrieved from disk)
`o2` always fails. (a retrofit call on an Android device that has no connectivity)

Given the documentation of concat, I think the overall `subscribe` should receive the element emitted by `o1`, then the error raised by `o2`. But in some occasion, it does **not** receive the item. It only receives the error, even though the log proves `o1` emitted at least one item.

**EDIT:** See below for the minimal code to reproduce the problem.

**Comment by JoanZapata** [comment] 2015-02-11 08:15
Here's the code to reproduce the problem:
(It's kotlin code but it only uses RxJava)

```kotlin
var busyScheduler = Schedulers.from(Executors.newSingleThreadExecutor());

// Make busyScheduler busy for 1 sec
Observable.create<Void>({ subscriber -> Thread.sleep(1000); subscriber.onCompleted() })
        .subscribeOn(busyScheduler)
        .subscribe()

// Create the 2 observables for concat
var o1 = Observable.just("Hello")
        .subscribeOn(Schedulers.newThread())
var o2 = Observable.error<String>(RuntimeException("Goodbye"))
        .subscribeOn(Schedulers.newThread())

// Concat them and observe the result on the busy scheduler
Observable.concat(o1, o2)
        .observeOn(busyScheduler)
        .subscribe(
                { print(Thread.currentThread().getName()); println(it) },
                { print(Thread.currentThread().getName()); it.printStackTrace() })
```

This never prints `Hello`. 
If I comment the part that makes ```busyScheduler``` busy, it workes as expected.

**Comment by akarnokd** [comment] 2015-02-11 11:14
Error propagation in observeOn cuts ahead of onNext values by design.

**Comment by JoanZapata** [comment] 2015-02-11 12:11
Do you mean it's the expected behavior? Is there any acceptable workaround on this?

**Comment by akarnokd** [comment] 2015-02-11 12:36
This is the expected behavior and there is no workaround.

**Comment by JoanZapata** [comment] 2015-02-11 14:13
Ok so I think I misunderstood `observeOn`.

> Error propagation in observeOn cuts ahead of onNext values by design.

Shouldn't it be documented ?

> there is no workaround

What about replacing:
```kotlin
Observable.concat(o1, o2).observeOn(scheduler)
```

.. with:
```kotlin
Observable.concat(o1.observeOn(scheduler), o2.observeOn(scheduler))
```

From what I can see, it seems to be working.

**Comment by DavidMGross** [comment] 2015-02-11 17:31
Documentation of this behavior will be in the next release of the Concat
operator web page.

On Wed, Feb 11, 2015 at 6:13 AM, Joan Zapata <notifications@github.com>
wrote:

> Ok so I think I misunderstood observeOn.
>
> Error propagation in observeOn cuts ahead of onNext values by design.
>
> Shouldn't it be documented ?
>
> there is no workaround
>
> What about replacing:
>
> Observable.concat(o1, o2).observeOn(scheduler)
>
> .. with:
>
> Observable.concat(o1.observeOn(scheduler), o2.observeOn(scheduler))
>
> From what I can see, it seems to be working.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ReactiveX/RxJava/issues/2646#issuecomment-73886557>.
>



-- 
David M. Gross
PLP Consulting

**Comment by JoanZapata** [comment] 2015-02-12 07:37
Given what @akarnokd said, I think it should rather be documented on the `observeOn` documentation.

**Comment by DavidMGross** [comment] 2015-02-12 18:10
I see what you mean. I'll add a note there as well.

On Wed, Feb 11, 2015 at 11:37 PM, Joan Zapata <notifications@github.com>
wrote:

> Given what @akarnokd <https://github.com/akarnokd> said, I think it
> should rather be documented on the observeOn documentation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ReactiveX/RxJava/issues/2646#issuecomment-74029417>.
>



-- 
David M. Gross
PLP Consulting

**Comment by akarnokd** [comment] 2015-05-20 09:07
I'm closing this due to inactivity. If you have further questions, don't hesitate to reopen this issue or post a new one.

**Closed by akarnokd** 2015-05-20 09:07 UTC
Labels: Question

**Comment by JoanZapata** [comment] 2015-05-20 10:20
No worry, the note was added on the documentation, thanks.

> Note that ObserveOn will forward an onError termination notification immediately if it receives one, and will not wait for a slow-consuming observer to receive any not-yet-emitted items that it is aware of first. This may mean that the onError notification jumps ahead of (and swallows) items emitted by the source Observable, as in the diagram above.
