### ISSUE TITLE
use retrofit Disposable already set!

### ISSUE THREAD

**Issue by lijiangdong** [ReactiveX/RxJava#5585] opened 2017-09-06 07:21 UTC
```
java.lang.IllegalStateException: Disposable already set!
	at io.reactivex.internal.disposables.DisposableHelper.reportDisposableSet(DisposableHelper.java:144)
	at io.reactivex.internal.disposables.DisposableHelper.setOnce(DisposableHelper.java:70)
	at io.reactivex.internal.operators.observable.ObservableTimer$IntervalOnceObserver.setResource(ObservableTimer.java:74)
	at io.reactivex.internal.operators.observable.ObservableTimer.subscribeActual(ObservableTimer.java:40)
	at io.reactivex.j.subscribe(Observable.java:10179)
	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.subscribeInner(ObservableFlatMap.java:162)
	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:139)
	at io.reactivex.internal.operators.observable.ax$a.onNext(ObservableMap.java:63)
	at io.reactivex.internal.operators.observable.bp$a.onNext(ObservableTakeWhile.java:90)
	at io.reactivex.internal.util.NotificationLite.accept(NotificationLite.java:246)
	at io.reactivex.subjects.a$a.test(BehaviorSubject.java:487)
	at io.reactivex.subjects.a$a.a(BehaviorSubject.java:482)
	at io.reactivex.subjects.a.onNext(BehaviorSubject.java:181)
	at io.reactivex.subjects.b.onNext(SerializedSubject.java:104)
	at io.reactivex.internal.operators.observable.ObservableRedo$RedoObserver.onError(ObservableRedo.java:107)
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onError(BodyObservable.java:72)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:55)
	at io.reactivex.j.subscribe(Observable.java:10179)
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
	at io.reactivex.j.subscribe(Observable.java:10179)
	at io.reactivex.internal.operators.observable.ObservableRedo$RedoObserver.handle(ObservableRedo.java:138)
	at io.reactivex.internal.operators.observable.ObservableRedo.subscribeActual(ObservableRedo.java:69)
	at io.reactivex.j.subscribe(Observable.java:10179)
	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.subscribeInner(ObservableFlatMap.java:162)
	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:139)
	at io.reactivex.internal.operators.observable.ah$a.onNext(ObservableFilter.java:51)
	at io.reactivex.internal.operators.observable.ObservableScalarXMap$ScalarDisposable.run(ObservableScalarXMap.java:246)
	at io.reactivex.internal.operators.observable.at.subscribeActual(ObservableJust.java:35)
	at io.reactivex.j.subscribe(Observable.java:10179)
	at io.reactivex.internal.operators.observable.ah.subscribeActual(ObservableFilter.java:29)
	at io.reactivex.j.subscribe(Observable.java:10179)
	at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
	at io.reactivex.j.subscribe(Observable.java:10179)
	at io.reactivex.internal.operators.observable.ax.subscribeActual(ObservableMap.java:32)
	at io.reactivex.j.subscribe(Observable.java:10179)
	at io.reactivex.internal.operators.observable.bb.subscribeActual(ObservableOnErrorNext.java:38)
	at io.reactivex.j.subscribe(Observable.java:10179)
	at io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver.drain(ObservableConcatMap.java:467)
	at io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver.onSubscribe(ObservableConcatMap.java:325)
	at io.reactivex.internal.operators.observable.aj.subscribeActual(ObservableFromArray.java:29)
	at io.reactivex.j.subscribe(Observable.java:10179)
	at io.reactivex.internal.operators.observable.ObservableConcatMap.subscribeActual(ObservableConcatMap.java:54)
	at io.reactivex.j.subscribe(Observable.java:10179)
	at io.reactivex.internal.operators.observable.bl.subscribeActual(ObservableSwitchIfEmpty.java:31)
	at io.reactivex.j.subscribe(Observable.java:10179)
	at io.reactivex.internal.operators.observable.bm.subscribeActual(ObservableTake.java:30)
	at io.reactivex.j.subscribe(Observable.java:10179)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$1.run(ObservableSubscribeOn.java:39)
	at io.reactivex.q$1.run(Scheduler.java:134)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)
```

**Comment by akarnokd** [comment] 2017-09-06 09:12
Please include the library version number, including the minor and patch version, in the issue text. In addition, if you'd include the major version in the title (such as `2.x`) that would be great.

If you think you found a bug, please include a code sample that reproduces the problem. Dumping a stacktrace is usually not enough for us.

**Comment by akarnokd** [comment] 2017-09-06 09:21
Looks like this is a duplicate #4927 fixed in **2.0.4** . Please upgrade to the latest version.

**Closed as completed by akarnokd** 2017-09-06 09:21 UTC
Labels: Duplicate, 2.x

**Comment by ganjasmara** [comment] 2017-12-06 12:48
Hi, this issue still happened on me, I'm using rxandroid 2.0.1 and rxjava 2.1.0

```
Fatal Exception: java.lang.IllegalStateException: Disposable already set!
       at io.reactivex.internal.disposables.DisposableHelper.reportDisposableSet(DisposableHelper.java:144)
       at io.reactivex.internal.disposables.DisposableHelper.setOnce(DisposableHelper.java:70)
       at io.reactivex.internal.operators.observable.ObservableTimer$IntervalOnceObserver.setResource(ObservableTimer.java:74)
       at io.reactivex.internal.operators.observable.ObservableTimer.subscribeActual(ObservableTimer.java:40)
       at io.reactivex.Observable.subscribe(Observable.java:10179)
       at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.subscribeInner(ObservableFlatMap.java:162)
       at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:139)
       at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:51)
       at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:63)
       at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onNext(ObservableCreate.java:67)
       at com.cantrowitz.rxbroadcast.RxBroadcast$2$1.onReceive(RxBroadcast.java:153)
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:768)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:149)
       at android.app.ActivityThread.main(ActivityThread.java:5257)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by akarnokd** [comment] 2017-12-06 12:54
@ganjasmara Please make sure the issue is present with the latest (2.1.7) version and if so, provide a code example that reproduces the problem.
