### ISSUE TITLE
JCTools as Shaded Dependency

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#1735] opened 2014-10-08 13:59 UTC
Now that JCTools is available on Maven Central (http://search.maven.org/#search%7Cga%7C1%7Cjctools) we should consider depending on it directly instead of copy/pasting as we have done so far: https://github.com/ReactiveX/RxJava/tree/1.x/src/main/java/rx/internal/util/unsafe (note the README that provides background and details).

There are a few considerations:

1) RxJava is a "zero dependency" project so the dependency will need to be shaded (package names changed to be inside RxJava) so that it becomes part of the RxJava jar.

2) Byte size of pulling in code from JCTools that we don't need. This affects Android particularly.

3) Use of JCTools must all be done behind a conditional check `UnsafeAccess.isUnsafeAvailable()` otherwise RxJava will not work on platforms without `sun.misc.Unsafe`.

**Comment by akarnokd** [comment] 2015-01-26 13:41
JCTools has different philosophy about when a queue is full. For example, trying to put 128 elements into an empty queue in response to a request can yield ```MissingBackpressureException``` because ```offer()``` returns false.

**Comment by nitsanw** [comment] 2015-01-28 15:09
@akarnokd I'm not sure which queue you are describing or what version... can you be more specific? Is this an issue in the copied over code? in v1.0? in trunk?

**Comment by akarnokd** [comment] 2015-01-28 15:21
@nitsanw There are so many versions flying around and my knowledge might be out of date or my perception misaligned. In PR #2541, the code I've copied meets our requirement, but I'm a bit cautious because what happened with SpscGrowableArrayQueue's capacity debate.

**Comment by nitsanw** [comment] 2015-01-28 15:33
@akarnokd part of the joy of development, SpscGrowableArrayQueue was prematurely released, and your help in debugging is appreciated. As discussed on that topic, the Queue interface does not support a capacity() method and the provided capacity in constructors is a open to some interpretation. General attitude in JCTools is that the capacity will be the larger or equal to the capacity prescribed, usually rounded to the nearest power of 2.

**Comment by akarnokd** [comment] 2015-01-28 15:56
Okay, given a power of 2 initial capacity of the queues, RxJava expects them to hold that amount of values exactly if there are no consumers.

**Comment by nitsanw** [comment] 2015-01-28 17:02
I wonder if having a capacity() method which lets you know what the actual capacity it would be a help?
I'm planning to release new Queue interfaces with the next version of JCTools.

**Comment by akarnokd** [comment] 2015-01-28 17:35
You misunderstand me. Any JCTools queue that we use has to pass the [following test](https://github.com/akarnokd/RxJava/blob/JCToolsUpgrade/src/test/java/rx/internal/util/unsafe/SpscArrayQueueTest.java).

**Comment by nitsanw** [comment] 2015-01-28 17:51
I understand, but I'm not sure I agree :-)

**Comment by benjchristensen** [comment] 2015-01-28 17:53
Just because our app needs this use case does not mean the underlying queue needs to support it outside the power of 2.

@akarnokd We can address this just by making it so our sizes are always a power of 2. This is why I've always stuck to a power of 2 for our sizing so that we don't have to layer an extra check on top and can just rely on `offer` to reject.

**Comment by nitsanw** [comment] 2015-01-28 17:57
So this means a queue which needs to be sized (2^n - 1) is unusable?

**Comment by akarnokd** [comment] 2015-01-28 17:58
It's not about the power of 2. Its about the the issue if the queue implementation decides it won't utilize the whole backing array. For example, a queue initialized with 128 capacity takes only 102 elements and rejects everything else because the internal implementation decided it keeps 16 elements space between head and tail.

**Comment by benjchristensen** [comment] 2015-01-28 18:25
@akarnokd  Ah, then yes that's a problem. If I provide a size I expect that to be the size available.

**Comment by nitsanw** [comment] 2016-03-01 11:13
Guys, I was under the impression this was done, but it seems to have been left to rot... please make time to resolve this.

**Comment by nitsanw** [comment] 2016-03-01 11:14
The full queue issue has been since tackled.

**Comment by nitsanw** [comment] 2016-03-02 09:31
@abersnaze and @stealthcode , you have been singled out by @akarnokd as the appropriate people to make aware of this. Your comments and feedback will be most welcome.

**Comment by stevegury** [comment] 2016-03-03 16:22
I started looking into this issue.
Using jctools directly makes all the [NPE tests](https://github.com/ReactiveX/RxJava/blob/1.x/src/test/java/rx/internal/util/JCToolsQueueTests.java#L75) fail.

@akarnokd you're more knowledgeable than me on that part, is that a problem?

**Comment by akarnokd** [comment] 2016-03-03 16:40
Maybe the JCTools throws IllegalArgumentException but RxJava generally throws and expects NPE.

**Comment by nitsanw** [comment] 2016-03-03 20:04
This is a bug in MPMC, I will fix and release shortly

**Comment by nitsanw** [comment] 2016-03-03 20:48
Fixed in master, I'll wrap into 1.2 release in the next week. MPMC was accepting, MpscLinked was throwing IllegalArg, I don't think you use either but might be wrong.

**Comment by stevegury** [comment] 2016-03-03 22:06
@NiteshKant Thanks for the quick change.
I confirmed that with the latest JCTools all the tests are passing.

I'll wait for your release.

**Comment by nitsanw** [comment] 2016-03-04 06:49
NP

**Comment by nitsanw** [comment] 2016-03-15 12:02
@stevegury JCTools 1.2 released. Let me know if anything else is required

**Comment by stevegury** [comment] 2016-03-15 23:55
Thanks @nitsanw I'll update my branch.

**Comment by nitsanw** [comment] 2016-03-24 07:16
Any news? anything I can do to help?

**Comment by akarnokd** [comment] 2016-03-24 09:33
Currently, the `combineLatest` operator uses a customized `SpscLinkedArrayQueue` where we have a method [offer(T, T)](https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/internal/util/atomic/SpscLinkedArrayQueue.java#L326) to post two objects at the same time without varargs and do non-spinning double poll() on the [receiving end](https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/internal/operators/OnSubscribeCombineLatest.java#L265). The pattern appears multiple times in 2.x as well.

This is kind of a Rx specific optimization/protocol. @nitsanw what's your take on such specific extensions to the JCTools API?

**Comment by nitsanw** [comment] 2016-03-24 10:30
@akarnokd as a general feature this seems to me like an atomic batch offer/poll. It's a slight variation on the current limited fill/drain interface and can be offered as extension. The current API relies on lambdas at the moment, but could be expanded to support (2,3, varargs) variants if a good argument can be made for it.

**Comment by guidomedina** [comment] 2016-03-27 14:15
About Unsafe availability you can do something similar to Netty, you can see the partial work I did for Netty to replace internal queues with JCtools, though I got stuck on the shade part but the Unsafe check is present:

https://github.com/guidomedina/netty/commit/7d1a621e8af4344fe18a910cdd5c7cb372390ad5

**Comment by nitsanw** [comment] 2016-05-29 16:22
@stevegury nudge?

**Comment by akarnokd** [comment] 2016-06-17 22:49
A PR is welcome setting this up, however, there are 3 problems that need addressing:
- We don't need all of JCTools' queue implementations; can the shading include/exclude classes?
- Currently, our SpscUnboundedArrayQueue offers a two argument offer(T, T) - no varargs, no lambdas.
- Some Android devices appear to be supporting Unsafe but then they crash at some point. We address this via a disable flag. Since we'd drop our UnsafeAccess, the [flag](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/disposables/Disposables.java) handling needs to be updated as well.

**Comment by guidomedina** [comment] 2016-06-18 08:00
This was successfully done at Netty, shade plugin only includes used classes, there are some atomic versions of these queues.

**Comment by guidomedina** [comment] 2016-06-18 09:50
This was successfully done at Netty:
- Shade plugin has an option to only include used classes.
- There are some atomic versions of these queues.

I would send a PR, but my Gradle knowledge is at most basic to get to the point of using a plugin, it was difficult enough in Maven because we had to also make the dependency optional for OSGI and available for tests on the parent pom.

For single producer/consumer, I would use the atomic version because one thread won't race against anything else hence no making a performance difference against `Unsafe`; the real difference when using `Unsafe` will come when using either multiple producer or consumer or both.

**Comment by guidomedina** [comment] 2016-06-18 09:55
For single producer/consumer, I would use the atomic version because one thread won't race against anything else hence no making a performance difference against `Unsafe`; the real difference when using `Unsafe` will come when using either multiple producer or consumer or both.

**Comment by nitsanw** [comment] 2016-06-18 10:06
@akarnokd I know the Gradle shade plugin is slightly flakier than the maven one, so that might prove a blocker here. You should be able to make this work using explicit includes/excludes.
The double arg SPSC is a usecase I plan to support via code generated channels, for now you might have to extend the class somehow or keep your variant.

@guidomedina The difference between Unsafe/Atomic performance is down to indirection costs. I think your intuition on this is incorrect. There's no difference in contention in principal, in fact using atomics may reduce contention because having slower consumer/producer code means the contended memory is hit less frequently.

**Comment by guidomedina** [comment] 2016-06-18 10:20
@nitsanw there are more ops to be made that I agree, but in practice you get a 100% hit rate on get, add or both hence making the difference in cost to tend to zero, I agree that my previous statement technically speaking was wrong but the practical difference is what?

That in the scenario of only one thread at head and tail concurrently.

**Comment by guidomedina** [comment] 2016-06-18 10:22
that in the context of only one thread at head and tail concurrently.

**Comment by nitsanw** [comment] 2016-06-18 14:05
@guidomedina please reflect your intended usecase in a JMH benchmark, let the numbers speak ;-)

**Comment by guidomedina** [comment] 2016-06-18 15:08
I understand that `Unsafe` is faster than doing atomic operations, mainly because of threads racing against one another and when an `get` or `set` fails it has to spin again, that's not what I'm arguing against.

I'm saying for this particular scenario _-single producer and single consumer-_ both operations will always succeed in the 1st attempt, there is some indirection which later will mitigated by JIT.

Is my assumption wrong?, but for the sake of an small argument let's say the cost _-again; single producer and single consumer-_ is of some percentage that might not be worth the effort trying to figure out if you should use `Unsafe` or not for an specific Android, in that case, you may well pay that price, what price are we talking? 5% slower? 10% slower? .... or 20%+?

I don't think it is going to reach such high level, and are in such uncharted territory that nobody has tested how fast an atomic operation is compared to Unsafe for a single thread?

**Comment by guidomedina** [comment] 2016-06-18 15:30
Ratio using Java8u92 i5-4670k after `Unsafe` has warmed up is 0.4 indicating for a single thread it is twice faster, but is that the same for Android?

**Comment by nitsanw** [comment] 2016-06-18 17:26
Post your benchmark as gist please.
Why do you think Unsafe is 2 times faster? Use -prof perfnorm and reason on counters?

**Comment by guidomedina** [comment] 2016-06-18 21:46
https://gist.github.com/guidomedina/d20381b55c89c641ccdb5e277edcd1b8

**Comment by nitsanw** [comment] 2016-07-22 13:38
Note that Netty now properly depends on JCTools. Also note recent improvements to SPSC linked array queues (not implemented in the atomic cases).

**Comment by akarnokd** [comment] 2016-07-22 16:29
@nitsanw 

> > // Sadly I see no good way to express the control flow below using inheritance.

I saw you unified a lot of implementations. I'd kept them separate so no excess but unused features sneak 
into the hot path. In addition, there are now extra fields and local variables which taxes the JIT and may not leave room for local variables outside the offer/poll.

Plus it still doesn't have two object offer which saves us a tuple allocation / spinning on a poll.

Btw, I'd be interested in a blog post about how the JIT's register allocator behaves when there are more locals than registers. I had odd and lower benchmark results in some drain loops: when I cached a final field, that was slower than reading the field in a loop, surrounded by unrelated volatile reads.

**Comment by nitsanw** [comment] 2016-07-22 18:22
@akarnokd I'm happy to discuss, but not all of your comment seems focused on this thread
"Plus it still doesn't have two object offer which saves us a tuple allocation / spinning on a poll." -> true

Unrelated:
"I saw you unified a lot of implementations. I'd kept them separate so no excess but unused features sneak into the hot path. " -> This is all in the offerColdPath. This is as bad as a bimorphic call, so no worse than inheritance, just uglier. There's 2 unused fields in the Unbounded case. Because there's no clean way to extend a class with layout control (I want extra fields in the producer fields clamp), this may not be easily avoidable. Can maybe reorder the inheritance order and add them in extension.
The implementation for Growable is much much simpler, and has a lot in common with the chunked, I think that worked out well. Overall code size has reduced. I've re-benchmarked and the results look good...
As for number of var/fields impact on register allocation, while in theory larger methods can confuse the register allocator in principal the number of registers on a typical CPU is quite high and running out of registers is not that common. The case you describe should be examined in isolation. I'd be happy to have a look.

**Comment by nitsanw** [comment] 2016-07-23 08:58
@akarnokd I played around with the impls some more. Reordered fields and specialized cold path. Perf looks good. Please give feedback in JCTools.

**Comment by akarnokd** [comment] 2017-10-18 14:19
Closing as this will likely not happen for 1.x. Subsequent versions have to use customized versions anyway.

**Closed by akarnokd** 2017-10-18 14:19 UTC
Labels: 1.x, Build, Enhancement, PR welcome
