### ISSUE TITLE
Add fromAsync() to the Creating Observables wiki

### ISSUE THREAD

**Issue by Egorand** [ReactiveX/RxJava#4200] opened 2016-07-14 06:29 UTC
Haven't found any info about the new `fromAsync()` operator in the [Creating Observables](https://github.com/ReactiveX/RxJava/wiki/Creating-Observables) wiki, can this be added? It would also be nice to have a note on why it should be preferred over `Observable.create()`, if it is the case. Thanks!

**Comment by DavidMGross** [comment] 2016-07-14 17:29
duplicate of ReactiveX/reactivex.github.io#277

On Wed, Jul 13, 2016 at 11:30 PM, Egor Andreevici notifications@github.com
wrote:

> Haven't found any info about the new fromAsync() operator in the Creating
> Observables
> https://github.com/ReactiveX/RxJava/wiki/Creating-Observables wiki, can
> this be added? It would also be nice to have a note on why it should be
> preferred over Observable.create(), if it is the case. Thanks!
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/ReactiveX/RxJava/issues/4200, or mute the thread
> https://github.com/notifications/unsubscribe/AESHoAfO2diNdGyPnBSnYt_9o--5SPs6ks5qVddpgaJpZM4JMH0b
> .

## 

David M. Gross
PLP Consulting

**Comment by Lakedaemon** [comment] 2016-08-13 21:40
I looked into fromAsync (the sparse javadoc with the usage snipet) but couldn't fathom how you were supposed to add a subscription to the emitter : 

I would like my listener to have an isUnsubscribed() method to be able to stop my Async function doing work early.

So, I looked into OnSubscribeFromAsync<T> and I saw that it created an emitter (in my case a  BufferAsyncEmitter<T>)  that implements a subscription and that it feeds into the Action1<AsyncEmitter<T>> ... 

So I might get away with a cast to a subscription inside my async api call (can't cast to the BufferAsyncEmitter, it isn't public) ... but it feels dirty and I probably don't understand how to correctly use setSubscription() (if I should use it or not).

So, could we have a better usage snipet, in the javadoc, that explains how to make the async call cancelable ? please ?

**Comment by akarnokd** [comment] 2016-08-14 07:20
There is a section about fromAsync on [StackOverflow docs](http://stackoverflow.com/documentation/rx-java/2341/backpressure/10629/creating-backpressured-data-sources). Until an `isUnsubscrribed()` is added, you can set any subscription container on the emitter and check its status.

**Comment by akarnokd** [comment] 2016-08-24 09:59
Updated the wiki.

**Closed as completed by akarnokd** 2016-08-24 09:59 UTC
Labels: Documentation
