### ISSUE TITLE
2.0.4 The merge operator throws an exception

### ISSUE THREAD

**Issue by summer88123** [ReactiveX/RxJava#4999] opened 2017-01-17 09:44 UTC
```
Single.merge(Single.<String>error(new RuntimeException("one")),
                Single.<String>error(new RuntimeException("two")))
                .subscribe(new Consumer<String>() {
                    @Override
                    public void accept(String s) throws Exception {
                        System.out.println(s);
                    }
                }, new Consumer<Throwable>() {
                    @Override
                    public void accept(Throwable throwable) throws Exception {
                        System.out.println(throwable.getMessage());
                    }
                });
```

The second Single is still executed and does not terminate with the first Single error.
In the 2.0.0-RC3 version, the zip operator has a similar problem, but was fixed in 2.0.0.

**Comment by akarnokd** [comment] 2017-01-17 09:53
Duplicate of #4991. The fix is already included in the snapshot and will be released with 2.0.5.

**Closed as completed** 2017-01-19 14:00 UTC
Labels: Duplicate, 2.x
